"""
The product catalogue a coverage measurement resolved against, named.

WHY THIS MODULE EXISTS. `scripts/check_recipe_coverage.py` resolved through
`InMemoryPriceRepository()`, which defaults to `fixtures/products.json` -- 26
products, 152 rows -- while `src/recipes/base.py` described the same
measurement as being against "300 items per store across 17 categories" and the
serving table held 2,759 rows of a different catalogue. The docstring named the
real catalogue; the code read the fixture one. A blocking decision on Req 2.9
rested on an instrument pointed at the wrong data, and nothing in its output
said which data that was.

The conclusion survived -- zero of the 175 imported recipes are fully priceable
against EITHER catalogue -- which is luck rather than design, and luck is not a
control. So the fix is the structural one this project already applies
everywhere else: **make the instrument name its inputs.** A `Catalogue` carries
its own source path and its own size, `describe()` prints them, and no caller
can report a coverage number without saying what it was measured against.

IT ALSO REMOVES A THIRD COPY. `Philip_demo/11_recipe_coverage_gate.py` and
`tests/test_curated_recipes.py` each carried their own loop over
`datasets/data/dynamodb_products` -- byte-for-byte equivalent apart from one
mapping to a product key and the other to a category. Equivalent copies are the
dangerous kind: nothing is wrong, so nothing flags the day one of them is
tuned. There is one loader now, and both mappings come off the same load.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

#: The data team's collected catalogue, transformed by `ingestion/lineage_b.py`.
#: This is what the deployed products table holds.
DATASET_DIR = ROOT / "datasets" / "data" / "dynamodb_products"

#: The 26-product seed catalogue with deliberately messy cross-store naming.
#: Generated by `scripts/generate_fixtures.py`; used by every offline test.
FIXTURE_PATH = ROOT / "fixtures" / "products.json"


@dataclass(frozen=True, slots=True)
class Catalogue:
    """
    A set of resolvable product keys, and the honest label for where they came
    from. Frozen because a measurement's inputs must not change under it.
    """

    #: Short label for output -- "datasets" or "fixtures".
    name: str
    #: Where it was read from, relative to the repository root.
    source: str
    #: Distinct product keys, which is what an ingredient term resolves TO.
    product_keys: frozenset[str]
    #: product_key -> dietary category, for viability checks.
    categories: Mapping[str, str]
    #: Store-rows read. Distinct from `len(product_keys)`: the same product in
    #: ten stores is ten rows and one key, and quoting the wrong one of those
    #: two is how "2,759 items" and "300 products" describe one file.
    rows: int

    def describe(self) -> str:
        return (
            f"{self.name} ({self.source}) -- "
            f"{len(self.product_keys)} distinct products, {self.rows} rows"
        )

    def resolve(self, term: str, synonyms: Mapping[str, list[str]]) -> str | None:
        """
        An ingredient term to a product key, exactly as `resolve_product_key`
        does it: normalise, try the synonym table, then the slugged term
        itself. Never a substring or nearest match -- see `design.md` §8.
        """
        from src.retrieval.memory import normalise_term

        normalised = normalise_term(term)
        for key in synonyms.get(normalised, []):
            if key in self.product_keys:
                return key
        direct = normalised.replace(" ", "-")
        return direct if direct in self.product_keys else None

    def category_for(self, term: str, synonyms: Mapping[str, list[str]]) -> str | None:
        key = self.resolve(term, synonyms)
        return self.categories.get(key) if key else None


def load_dataset_catalogue(directory: Path | None = None) -> Catalogue | None:
    """
    The real catalogue, or `None` when the dataset is not checked out.

    Returning `None` rather than falling back to fixtures is the point of the
    module: a caller that cannot read the real catalogue must say so, not
    quietly report a fixture number under a real-catalogue heading.
    """
    directory = directory or DATASET_DIR
    if not directory.exists():
        return None

    from ingestion.lineage_b import classify, derive_product_key, is_non_food

    categories: dict[str, str] = {}
    rows = 0
    for path in sorted(directory.glob("*.json")):
        for entry in json.loads(path.read_text(encoding="utf-8"))["SmartGroceryProducts"]:
            item = entry.get("PutRequest", {}).get("Item", entry)
            record = {k: (v.get("S") if "S" in v else v.get("N")) for k, v in item.items()}
            if is_non_food(record["product_name"]):
                continue
            rows += 1
            key = derive_product_key(record["product_name"], record.get("size", ""))
            categories[key] = classify(record["product_name"], record["category"])[0]

    return Catalogue(
        name="datasets",
        source=str(directory.relative_to(ROOT)).replace("\\", "/"),
        product_keys=frozenset(categories),
        categories=categories,
        rows=rows,
    )


def load_fixture_catalogue(path: Path | None = None) -> Catalogue:
    """
    The 26-product seed catalogue. Always present; it is committed.

    The file is a flat list of store-rows, so the same product appears once per
    store that stocks it -- which is exactly the distinction `rows` exists to
    keep: 152 rows, 26 products.
    """
    path = path or FIXTURE_PATH
    records = json.loads(path.read_text(encoding="utf-8"))
    categories = {r["product_key"]: r.get("category", "") for r in records}

    return Catalogue(
        name="fixtures",
        source=str(path.relative_to(ROOT)).replace("\\", "/"),
        product_keys=frozenset(categories),
        categories=categories,
        rows=len(records),
    )
